version: '3.4'
services:
  ################################################################################
  # Headless browser, used by the test suite to actually run the tests against the
  # containers.
  selenium-chrome:
    image: selenium/standalone-chrome:123.0
    ports:
      - 4444:4444

  ################################################################################
  mongodb:
    image: mongo:6
    volumes:
      - ./docker/scripts/mongodb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.hello().ok']
      interval: 5s
      start_period: 5s
      retries: 3
  ################################################################################
  localstack:
    image: localstack/localstack:3.2.0
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - SERVICES=s3,sqs,sns,dynamodb
      - LS_LOG=WARN
    env_file:
      - ./docker/config/defaults.env
    volumes:
      - ./docker/scripts/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3

  ################################################################################
  redis:
    image: redis:7
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'PING']
      interval: 5s
      start_period: 2s
      retries: 5
  ################################################################################
  #
  # Add the services you want to test below.
  #
  ################################################################################
  your-frontend:
    image: defradigital/assurance-frontend:latest
    ports:
      - '3000:3000'
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
      your-backend:
        condition: service_started
    env_file:
      - 'compose/aws.env'
    environment:
      API_BASE_URL: http://your-backend:8080
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_CLIENT_ID: 'a741690c-cc36-410d-a83a-b64a1bbc635a'
      AZURE_TENANT_ID: '6f504113-6b64-43f2-ade9-242e05780007'
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      LOCALSTACK_ENDPOINT: http://localstack:4566
      USE_SINGLE_INSTANCE_CACHE: true
    networks:
      - default
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ################################################################################
  your-backend:
    image: defradigital/assurance-api:latest
    ports:
      - '8080:8080'
    depends_on:
      mongodb:
        condition: service_healthy
      localstack:
        condition: service_healthy
    environment:
      PORT: 8080
      NODE_ENV: development
      AZURE__TENANTID: '6f504113-6b64-43f2-ade9-242e05780007'
      AZURE__CLIENTID: 'a741690c-cc36-410d-a83a-b64a1bbc635a'
      AUTO_GENERATE_HISTORY: true
      LOCALSTACK_ENDPOINT: http://localstack:4566
      Mongo__DatabaseUri: mongodb://mongodb:27017
    networks:
      - default
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

################################################################################
# Networks
networks:
  default:
    driver: bridge
